"""
GENZ HR — Template Engine
Handles HR document generation with dynamic variable substitution.
Supports: Markdown, JSON, DOCX (via python-docx), plain text.
"""
import re
import json
from pathlib import Path
from datetime import datetime
from typing import Optional
from jinja2 import Environment, BaseLoader, Undefined

from backend.core.config import get_company_dir


# ─── Built-in Template Library ────────────────────────────────────────────────

BUILTIN_TEMPLATES = {
    "offer_letter": """
# OFFER LETTER

**Date:** {{date}}

Dear {{employee_name}},

We are delighted to offer you the position of **{{position}}** at **{{company_name}}**.

## Terms of Offer

| Item | Details |
|------|---------|
| Position | {{position}} |
| Department | {{department}} |
| Start Date | {{start_date}} |
| Employment Type | {{employment_type}} |
| Monthly Gross Salary | ₦{{salary}} |
| Probation Period | {{probation_period}} |
| Reporting To | {{manager_name}} |

## Benefits

- Pension contribution (Employer: 10%, Employee: 8%)
- {{benefits}}

This offer is subject to satisfactory reference checks and execution of the Employment Contract.

Please confirm acceptance by {{acceptance_deadline}}.

Yours sincerely,

**{{hr_signatory}}**  
HR Department, {{company_name}}
""",

    "employment_contract": """
# EMPLOYMENT CONTRACT

**Between:** {{company_name}} ("the Company")  
**And:** {{employee_name}} ("the Employee")

## 1. Position and Duties

The Employee is engaged as **{{position}}** in the {{department}} department, 
reporting to {{manager_name}}, effective {{start_date}}.

## 2. Remuneration

Monthly gross salary: **₦{{salary}}**  
Payable on the {{payment_day}} of each month via bank transfer.

Statutory deductions apply per Nigerian law:
- PAYE Tax (Finance Act 2020)
- Pension (PRA 2014) — Employee: 8%, Employer: 10%
- NHF (NHF Act) — 2.5% of basic salary

## 3. Working Hours

Standard hours: {{working_hours}} per week.  
{{remote_policy}}

## 4. Leave Entitlement

- Annual Leave: {{annual_leave_days}} working days per year
- Sick Leave: {{sick_leave_days}} working days per year  
- Public Holidays as gazetted by the Federal Government of Nigeria

## 5. Termination

Either party may terminate this contract by giving {{notice_period}} written notice,  
or payment in lieu of notice.

## 6. Confidentiality

The Employee agrees to maintain strict confidentiality of all Company information  
during and after employment.

## 7. Governing Law

This contract is governed by the laws of the Federal Republic of Nigeria,  
including the Labour Act (Cap L1 LFN 2004).

---

**Signed by the Company:**

Name: {{hr_signatory}}  
Date: {{date}}

**Signed by the Employee:**

Name: {{employee_name}}  
Date: _______________
""",

    "task_sheet": """
# TASK SHEET — {{period}}

**Employee:** {{employee_name}}  
**Position:** {{position}}  
**Department:** {{department}}  
**Period:** {{period}}  
**Generated:** {{date}}

## Assigned Tasks

| # | Task Description | Weight | Due Date | Status | Score |
|---|-----------------|--------|----------|--------|-------|
{{task_rows}}

## Performance Targets

- Minimum completion required: **{{min_completion}}%**
- Bonus eligibility threshold: **{{bonus_threshold}}%**

## Instructions

1. Update task status by end of each day
2. Add comments for any blockers
3. Submit completed sheet to your team lead by {{submission_deadline}}

## Team Lead Feedback

_To be completed by {{manager_name}}_

Overall Assessment: _______________  
Areas of Strength: _______________  
Areas for Improvement: _______________

---
_Generated by GENZ HR Agent — Subject to Esther's review_
""",

    "payslip": """
# PAYSLIP — {{period}}

**{{company_name}}**

---

| Field | Value |
|-------|-------|
| Employee Name | {{employee_name}} |
| Employee ID | {{employee_id}} |
| Position | {{position}} |
| Department | {{department}} |
| Pay Period | {{period}} |
| Bank | {{bank_name}} |
| Account | {{account_number}} |

## Earnings

| Item | Amount (₦) |
|------|------------|
| Basic Salary | {{basic_salary}} |
| Housing Allowance | {{housing_allowance}} |
| Transport Allowance | {{transport_allowance}} |
| Other Allowances | {{other_allowances}} |
| Performance Bonus | {{performance_bonus}} |
| **Gross Salary** | **{{gross_salary}}** |

## Deductions

| Item | Amount (₦) |
|------|------------|
| PAYE Tax | {{paye_tax}} |
| Pension (Employee 8%) | {{pension_employee}} |
| NHF (2.5% Basic) | {{nhf_deduction}} |
| Other Deductions | {{other_deductions}} |
| **Total Deductions** | **{{total_deductions}}** |

---

## **NET SALARY: ₦{{net_salary}}**

---
_This payslip is computer-generated and valid without signature._  
_Generated by GENZ HR — Approved by Esther_
""",

    "performance_report": """
# PERFORMANCE REPORT — {{period}}

**Employee:** {{employee_name}}  
**Position:** {{position}}  
**Department:** {{department}}  
**Reviewed By:** {{reviewer_name}}  
**Period:** {{period}}

## Performance Summary

| Metric | Score |
|--------|-------|
| Task Completion | {{task_completion}}% |
| Quality Score | {{quality_score}}/100 |
| Attendance Score | {{attendance_score}}/100 |
| Overall Performance | **{{overall_score}}/100** |

## Detailed Analysis

{{ai_analysis}}

## Recommendations

{{recommendations}}

## Development Plan

{{development_plan}}

---
_AI-generated report. Reviewed and approved by {{reviewer_name}}_
""",
}


# ─── Template Engine ───────────────────────────────────────────────────────────

class GenZTemplateEngine:
    """Renders GENZ HR templates with dynamic variable substitution."""

    def __init__(self):
        self.env = Environment(
            loader=BaseLoader(),
            undefined=Undefined,
        )

    def render(self, template_content: str, variables: dict) -> str:
        """
        Replace {{variable}} placeholders with actual values.
        Uses Jinja2 under the hood but supports {{var}} syntax.
        """
        # Convert {{var}} to {{ var }} for Jinja2
        jinja_content = re.sub(r"\{\{(\w+)\}\}", r"{{ \1 }}", template_content)

        # Add default values for common fields
        defaults = {
            "date": datetime.now().strftime("%d %B %Y"),
            "probation_period": "3 months",
            "payment_day": "28th",
            "notice_period": "1 month",
            "annual_leave_days": "6",
            "sick_leave_days": "10",
            "working_hours": "40 hours",
            "remote_policy": "Hybrid work arrangement applies.",
            "benefits": "Health Insurance, Group Life Insurance",
            "hr_signatory": "HR Manager",
        }
        context = {**defaults, **variables}

        try:
            template = self.env.from_string(jinja_content)
            return template.render(**context)
        except Exception as e:
            # Fallback: simple string replacement
            result = template_content
            for key, val in context.items():
                result = result.replace(f"{{{{{key}}}}}", str(val))
            return result

    def render_builtin(self, template_type: str, variables: dict) -> str:
        """Render a built-in template."""
        if template_type not in BUILTIN_TEMPLATES:
            raise ValueError(f"Unknown template type: {template_type}. "
                             f"Available: {list(BUILTIN_TEMPLATES.keys())}")
        return self.render(BUILTIN_TEMPLATES[template_type], variables)

    def render_task_sheet(self, employee: dict, tasks: list[dict], period: str) -> str:
        """Special renderer for task sheets with task table generation."""
        task_rows = ""
        for i, task in enumerate(tasks, 1):
            task_rows += (
                f"| {i} | {task.get('description', '')} | "
                f"{task.get('weight', 10)}% | "
                f"{task.get('due_date', 'End of period')} | "
                f"{task.get('status', 'Pending')} | "
                f"{task.get('score', '—')} |\n"
            )

        variables = {
            **employee,
            "period": period,
            "task_rows": task_rows,
            "min_completion": "70",
            "bonus_threshold": "90",
            "submission_deadline": "Last Friday of period",
        }
        return self.render_builtin("task_sheet", variables)

    def extract_variables(self, content: str) -> list[str]:
        """Extract all {{variable}} names from a template."""
        return list(set(re.findall(r"\{\{(\w+)\}\}", content)))

    def validate_template(self, content: str, provided_vars: dict) -> dict:
        """Check which required variables are missing."""
        required = self.extract_variables(content)
        missing = [v for v in required if v not in provided_vars]
        return {
            "valid": len(missing) == 0,
            "required_variables": required,
            "missing_variables": missing,
        }

    def save_template(self, company_id: str, template_name: str, content: str, template_type: str = "custom"):
        """Save a rendered or custom template to the company folder."""
        from backend.core.config import get_company_dir
        company_dir = get_company_dir(company_id)
        template_dir = company_dir / "templates"
        template_dir.mkdir(exist_ok=True)
        
        filename = f"{template_name.lower().replace(' ', '_')}.md"
        filepath = template_dir / filename
        filepath.write_text(content, encoding="utf-8")
        return str(filepath)


# Singleton instance
template_engine = GenZTemplateEngine()
